import { inicializarFecha } from './modules/fecha.js';
import { inicializarMensajeDelDia } from './modules/mensaje-diario.js';
import { inicializarChecklist } from './modules/checklist.js';
import { inicializarVencimientos } from './modules/vencimientos.js';
import { inicializarNotificaciones } from './modules/notificaciones.js';
import { registrarServiceWorker } from './modules/sw-register.js';
import { inicializarEstadoFormularios } from './modules/estado-formularios.js';
import { inicializarBaseDatosVencimientos } from './modules/vencimientos-db.js';
import { inicializarEnlaces } from './modules/enlaces.js';
import { inicializarEscaner } from './modules/escaner.js';
import { inicializarSesionUI } from './modules/sesion-ui.js';
import { inicializarAutenticacion } from './modules/auth.js';
import { inicializarFiltros } from './modules/filtros.js';
import { inicializarTopProductos } from './modules/top-productos.js';
import { inicializarRankingUsuarios } from './modules/ranking-usuarios.js';
import { inicializarSidebar } from './modules/sidebar.js';
import { inicializarInstaladorPWA } from './modules/install.js';
import { inicializarReportes } from './modules/reportes.js';
import { inicializarFirebase } from './firebase/firebase.js';

document.addEventListener('DOMContentLoaded', async () => {
    await inicializarFirebase();
    inicializarAutenticacion();
    inicializarFecha();
    inicializarMensajeDelDia();
    inicializarSidebar();
    inicializarEnlaces();
    inicializarEstadoFormularios();
    inicializarInstaladorPWA();
    registrarServiceWorker();
    inicializarChecklist();
    inicializarFiltros();
    inicializarEscaner();
    inicializarSesionUI();
    inicializarReportes();
    inicializarVencimientos();
    inicializarBaseDatosVencimientos();
    inicializarNotificaciones();
    inicializarTopProductos();
    inicializarRankingUsuarios();
    inicializarMensajeDelDia();
});